DEFAULT_METHOD
DEFAULT_TIMEZONE
DEFAULT_LANGUAGE

```python
DOMAIN = "ha_zmanim_pro"

CONF_NAME = "name"
CONF_LATITUDE = "latitude"
CONF_LONGITUDE = "longitude"
CONF_TIMEZONE = "timezone"

DEFAULT_NAME = "Zmanim Pro"
DEFAULT_UPDATE_INTERVAL = 300
```
